### ISSUE TITLE
Slash commands are not registering 

### ISSUE THREAD

**Issue by CylinderMan** [FalloutStudios/Reciple#33]
I have uninstalled reciple, reinstalled reciple, created a new template, created a new bot and still it doesn't register commands. I have made sure the bot has every single permission, what is going on?

![Screenshot 2023-08-14 181731](https://github.com/FalloutStudios/Reciple/assets/111149585/a9bfe422-6cf4-446d-a69e-8e05b1026f72)

**Comment by NotGhex** [comment]
@CylinderMan try updating reciple to version 7.9.9 and tell me if it's fixed

**Comment by CylinderMan** [comment]
Thank you it works now!
